### ISSUE TITLE
Tweaks to the Codebase

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openbeautyfacts#6]
- [ ] Replace "Nutrition Facts" by "Composition"
- [ ] Replace "Open Food Facts" by "Open Beauty Facts"
- [ ] Replace logos
- [ ] Change links to apps
- [ ] Change wiki url (including for autoimport)
- [ ] Load categories taxonomy from Open Beauty Facts wiki

**Comment by TaciteOFF** [comment]
What will be "composition" as opposed to ingredients?

**Comment by teolemon** [comment]
not quite sure, percentage if we have them ?
otherwise, we may remove the section alltogether and replace it by a longer explanation of each of the ingredients, in context, with regard to the category (different impact if lipstick or cream)

**Comment by teolemon** [comment]
This bug was broken into sub-bugs. Closing.
