### ISSUE TITLE
Authentication not working to https://en.wiki.openbeautyfacts.org

### ISSUE THREAD

**Issue by SantosSi** [openfoodfacts/openbeautyfacts#71]
With https://de.openbeautyfacts.org logged in opening the https://de.wiki.openbeautyfacts.org or https://en.wiki.openbeautyfacts.org does not authenticate to change the wiki content.
The same actions and web browser used in openfoodfacts work fine.

**Comment by teolemon** [comment]
We merged the wikis. This is solved as a result.
