### ISSUE TITLE
OBF Android app 3.1.2 crashes when swiping  to ingredients

### ISSUE THREAD

**Issue by SantosSi** [openfoodfacts/openbeautyfacts#73]
How to recreate: Scan a product, swipe right to the next tab ingredients, the app crashes.

**Comment by teolemon** [comment]
Does it have a portion ?

**Comment by SantosSi** [comment]
It has no portion and no nutrition information. Example product: https://de.openbeautyfacts.org/produkt/4058172169557/haarspray-volumen-effekt-4-feines-haar-balea

**Comment by teolemon** [comment]
fixed
