### ISSUE TITLE
Translate OBF logo to Hebrew

### ISSUE THREAD

**Issue by yarons** [openfoodfacts/openbeautyfacts#74]
### What

This is the English version of the logo, I need to create a Hebrew version of it in order to make the localization complete:
https://world.openbeautyfacts.org/images/misc/openbeautyfacts-logo-en.png

How can I do it?
Can I add some instructions for other translators that will want to do it in the future?

Thanks.
### Part of
- #75

**Comment by teolemon** [comment]
https://www.figma.com/file/W0bZxCk11s85MmRZBTYk5X/?node-id=3%3A2
Having a wiki page for graphic asset translation would be nice

**Comment by yarons** [comment]
@teolemon Sadly there's no RTL support :(

**Comment by teolemon** [comment]
The new logo fixes that: 
https://raw.githubusercontent.com/openfoodfacts/openbeautyfacts/develop/logos/LOGO_OBF_RVB9.svg
