### ISSUE TITLE
Ensure we can parse this new separator in the ingredients

### ISSUE THREAD

**Issue by TaciteOFF** [openfoodfacts/openbeautyfacts#9]
A lot of cosmetics have a "middle bullet" symbol to separate ingredients : 

•

It's not yet parsed, as you can see here : 

http://fr.openbeautyfacts.org/ingredient/aqua-water-sodium-laureth-sulfate-peg-8-coco-betaine-hexylene-glycol-sodium-chloride-peg-120-methyl-glucose-dioleate-zinc-pca-sodium-hydroxlde-citric-acid-sodium-benzoate-phenoxyethanol-caprylyl-glycol-parfum-fragrance

**Comment by stephanegigandet** [comment]
Fixed. Let me know if you see other separators.

**Comment by teolemon** [comment]
This one:
http://fr.openbeautyfacts.org/produit/3600521964705/glam-shine-601-l-oreal-paris
There are dots between ingredients.

**Comment by TaciteOFF** [comment]
Beware of dots that could be between numbers in percentages
